export let Data = [
    {
        image : 'virtual_reality.png',
        title : 'Augumented & Virtual Reality',
        service1 : 'AR VR MR Applications',
        service2 : 'Spatial Computing Solutions',
        service3 : 'Industrial AR VR Solutions',
        service4 : 'simulated Training Environments',
        service5 : 'Motion Platforms',
        service6 : '3D Visualization Services',
        service7 : 'Digital Twin',
    },
    {
        image : 'ai.png',
        title : 'Artificial Intelligence & Machine Learning',
        service1 : 'Customized Video Analytics',
        service2 : 'Autonomous Surveillance',
        service3 : 'Generative AI Solutions',
        service4 : 'Customized GPT based Chatbot',
        service5 : 'Quality Control and Defect Detection',
        service6 : 'Worker Safety Monitoring',
    },
    {
        image : 'web_app_development.png',
        title : 'Web & App Development',
        service1 : 'Web Application Development',
        service2 : 'Website',
        service3 : 'Custom Software Solutions',
        service4 : 'Special Tools',
        service5 : 'Internet of Things (loT) Integration',
        service6 : 'Cybersecurity',
    },
    {
        image : 'robot_operating_system.png',
        title : 'Robotics',
        service1 : 'Warehousing and Logistics Robots',
        service2 : 'Robotic Inspection and Surveillance',
        service3 : 'Commercial Mobile Robots',
        service4 : 'Robotic Command Center',
        service5 : 'ROS Solutions',
        service6 : 'Web Solutions for ROS',
    },
]